# Generated by Django 5.1.6 on 2025-05-01 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_jurusan", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dosen",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dosen_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nik", models.CharField(max_length=50, unique=True)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dosen",
                        to="users.jurusan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramStudi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_prodi", models.CharField(max_length=255, unique=True)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_studi",
                        to="users.jurusan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mahasiswa_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nim", models.CharField(max_length=50, unique=True)),
                (
                    "program_studi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mahasiswa",
                        to="users.programstudi",
                    ),
                ),
            ],
        ),
    ]
