# Generated by Django 5.2 on 2025-06-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahasiswa",
            name="dosen_pembimbing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mahasiswa_binaan",
                to="users.dosen",
            ),
        ),
    ]
