# Generated by Django 5.2 on 2025-06-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_historicaldosen_historicalmahasiswa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmahasiswa",
            name="dosen_pembimbing",
        ),
        migrations.RemoveField(
            model_name="historicalmahasiswa",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmahasiswa",
            name="program_studi",
        ),
        migrations.RemoveField(
            model_name="historicalmahasiswa",
            name="user",
        ),
        migrations.DeleteModel(
            name="HistoricalDosen",
        ),
        migrations.DeleteModel(
            name="HistoricalMahasiswa",
        ),
    ]
