# Generated by Django 5.2 on 2025-06-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_activitylog_content_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
