# Generated by Django 5.1.6 on 2025-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requestdosen",
            old_name="mahasiswa_message",
            new_name="alasan_memilih_dosen",
        ),
        migrations.AddField(
            model_name="requestdosen",
            name="rencana_deskripsi",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="requestdosen",
            name="rencana_judul",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
