# Generated by Django 5.2 on 2025-06-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tugas_akhir",
            "0002_rename_mahasiswa_message_requestdosen_alasan_memilih_dosen_and_more",
        ),
        ("users", "0002_mahasiswa_dosen_pembimbing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dokumen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bab",
                    models.CharField(
                        choices=[
                            ("BAB I", "BAB I - Pendahuluan"),
                            ("BAB II", "BAB II - Tinjauan Pustaka"),
                            ("BAB III", "BAB III - Metodologi Penelitian"),
                            ("BAB IV", "BAB IV - Hasil dan Pembahasan"),
                            ("BAB V", "BAB V - Kesimpulan dan Saran"),
                            ("LAMPIRAN", "Lampiran"),
                        ],
                        help_text="Chapter of the document",
                        max_length=50,
                    ),
                ),
                (
                    "nama_dokumen",
                    models.CharField(
                        help_text="Name of the document file", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file", upload_to="dokumen_ta/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Revisi", "Revisi"),
                            ("Disetujui", "Disetujui"),
                        ],
                        default="Pending",
                        help_text="Approval status of the document",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pemilik",
                    models.ForeignKey(
                        help_text="The student who owns this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumen_mahasiswa",
                        to="users.mahasiswa",
                    ),
                ),
                (
                    "tugas_akhir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumen",
                        to="tugas_akhir.tugasakhir",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dokumen",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
