# Generated by Django 5.2 on 2025-06-21 23:02

import django.core.validators
import tugas_akhir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0003_dokumen"),
        ("users", "0002_mahasiswa_dosen_pembimbing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokumen",
            name="file",
            field=models.FileField(
                help_text="The uploaded document file",
                upload_to="dokumen_ta/",
                validators=[
                    tugas_akhir.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"],
                        message="File harus dalam format PDF.",
                    ),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="dokumen",
            constraint=models.UniqueConstraint(
                fields=("pemilik", "bab"), name="unique_bab_per_mahasiswa"
            ),
        ),
    ]
