# Generated by Django 5.2 on 2025-06-22 04:00

import django.core.validators
import django.db.models.deletion
import simple_history.models
import tugas_akhir.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0004_alter_dokumen_file_dokumen_unique_bab_per_mahasiswa"),
        ("users", "0003_historicaldosen_historicalmahasiswa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDokumen",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "bab",
                    models.CharField(
                        choices=[
                            ("BAB I", "BAB I - Pendahuluan"),
                            ("BAB II", "BAB II - Tinjauan Pustaka"),
                            ("BAB III", "BAB III - Metodologi Penelitian"),
                            ("BAB IV", "BAB IV - Hasil dan Pembahasan"),
                            ("BAB V", "BAB V - Kesimpulan dan Saran"),
                            ("LAMPIRAN", "Lampiran"),
                        ],
                        help_text="Chapter of the document",
                        max_length=50,
                    ),
                ),
                (
                    "nama_dokumen",
                    models.CharField(
                        help_text="Name of the document file", max_length=255
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        help_text="The uploaded document file",
                        max_length=100,
                        validators=[
                            tugas_akhir.models.validate_file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"],
                                message="File harus dalam format PDF.",
                            ),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Revisi", "Revisi"),
                            ("Disetujui", "Disetujui"),
                        ],
                        default="Pending",
                        help_text="Approval status of the document",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pemilik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The student who owns this document",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="users.mahasiswa",
                    ),
                ),
                (
                    "tugas_akhir",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tugas_akhir.tugasakhir",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dokumen",
                "verbose_name_plural": "historical Dokumen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
