# Generated by Django 5.2 on 2025-06-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0005_historicaldokumen"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalDokumen",
        ),
    ]
