# Generated by Django 5.2 on 2025-06-23 20:46

import django.core.validators
import storages.backends.s3
import tugas_akhir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0006_delete_historicaldokumen"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokumen",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="dokumen",
            name="file",
            field=models.FileField(
                help_text="The uploaded document file",
                storage=storages.backends.s3.S3Storage(),
                upload_to="dokumen_ta/",
                validators=[
                    tugas_akhir.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"],
                        message="File harus dalam format PDF.",
                    ),
                ],
            ),
        ),
    ]
