# Generated by Django 5.2 on 2025-06-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0007_dokumen_file_hash_alter_dokumen_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokumen",
            name="catatan_revisi",
            field=models.TextField(
                blank=True,
                help_text="Catatan dari dosen jika statusnya adalah Revisi",
                null=True,
            ),
        ),
    ]
