# Generated by Django 5.2 on 2025-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tugas_akhir", "0008_dokumen_catatan_revisi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dokumen",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Revisi", "Revisi"),
                    ("Disetujui", "Disetujui"),
                ],
                db_index=True,
                default="Pending",
                help_text="Approval status of the document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requestdosen",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
