# Generated by Django 5.2 on 2025-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pengumuman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul",
                    models.CharField(help_text="Judul pengumuman", max_length=255),
                ),
                (
                    "deskripsi",
                    models.TextField(help_text="Isi lengkap dari pengumuman"),
                ),
                (
                    "tanggal_mulai",
                    models.DateField(help_text="Tanggal pengumuman mulai ditampilkan"),
                ),
                (
                    "tanggal_selesai",
                    models.DateField(help_text="Tanggal pengumuman berakhir"),
                ),
                (
                    "lampiran",
                    models.FileField(
                        blank=True,
                        help_text="File lampiran opsional",
                        null=True,
                        upload_to="attachments/announcements/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pengumuman",
                "verbose_name_plural": "Pengumuman",
                "ordering": ["-tanggal_mulai"],
            },
        ),
    ]
