# Generated by Django 5.2 on 2025-06-22 04:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPengumuman",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "judul",
                    models.CharField(help_text="Judul pengumuman", max_length=255),
                ),
                (
                    "deskripsi",
                    models.TextField(help_text="Isi lengkap dari pengumuman"),
                ),
                (
                    "tanggal_mulai",
                    models.DateField(help_text="Tanggal pengumuman mulai ditampilkan"),
                ),
                (
                    "tanggal_selesai",
                    models.DateField(help_text="Tanggal pengumuman berakhir"),
                ),
                (
                    "lampiran",
                    models.TextField(
                        blank=True,
                        help_text="File lampiran opsional",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pengumuman",
                "verbose_name_plural": "historical Pengumuman",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
