# Generated by Django 5.2 on 2025-06-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_historicalpengumuman"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPengumuman",
        ),
    ]
