# Generated by Django 5.2 on 2025-06-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_delete_historicalpengumuman"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengumuman",
            name="lampiran_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
