# Generated by Django 5.2.3 on 2025-06-23 22:22

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_pengumuman_lampiran_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengumuman",
            name="lampiran",
            field=models.FileField(
                blank=True,
                help_text="File lampiran opsional",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="attachments/announcements/",
            ),
        ),
    ]
