# tugas_akhir/api_urls.py
from django.urls import path, include
from rest_framework import generics, permissions
from rest_framework.routers import DefaultRouter
from . import api_views

# A router for the API endpoints (DokumenViewSet)
router = DefaultRouter()
router.register(r'dokumen', api_views.DokumenViewSet, basename='dokumen-api')
router.register(r'jadwal-bimbingan', api_views.JadwalBimbinganViewSet, basename='jadwal-bimbingan-api')

urlpatterns = [
    # --- Dosen-specific endpoints ---
    path('dosen/supervised-students/', api_views.SupervisedStudentsListView.as_view(), name='dosen-supervised-students'),

    # URL for supervision requests API
    path('supervision-requests/', api_views.SupervisionRequestListCreateView.as_view(), name='supervision-request-list-create'),
    path('supervision-requests/<int:pk>/', api_views.SupervisionRequestDetailUpdateView.as_view(), name='supervision-request-detail-update'),

    # URL to get a list of all available rooms
    path('ruangan/', generics.ListAPIView.as_view(
        queryset=api_views.Ruangan.objects.all(),
        serializer_class=api_views.RuanganSerializer,
        permission_classes=[permissions.IsAuthenticated]
    ), name='ruangan-list-api'),

    # Includes all URLs generated by the router for the Dokumen API (e.g., /dokumen/, /dokumen/{pk}/)
    path('', include(router.urls)),
]