# tugas_akhir/api_urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import api_views

# A router for the API endpoints (DokumenViewSet)
router = DefaultRouter()
router.register(r'dokumen', api_views.DokumenViewSet, basename='dokumen-api')

urlpatterns = [
    # URL for supervision requests API
    path('supervision-requests/', api_views.SupervisionRequestListCreateView.as_view(), name='supervision-request-list-create'),
    path('supervision-requests/<int:pk>/', api_views.SupervisionRequestDetailUpdateView.as_view(), name='supervision-request-detail-update'),

    # Includes all URLs generated by the router for the Dokumen API (e.g., /dokumen/, /dokumen/{pk}/)
    path('', include(router.urls)),
]